resources:
  repositories:
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

extends:
  template: v2/OneBranch.Official.CrossPlat.yml@templates # https://aka.ms/obpipelines/templates
  parameters:
    stages:
    - stage: main_stage
      jobs:
      - job: Build_Job
        pool:
          type: windows
        variables: # More settings at https://aka.ms/obpipelines/yaml/jobs
          ob_outputDirectory: '$(Build.SourcesDirectory)\drop'
        steps:
        - pwsh: ./build.ps1
          displayName: Build_Step
