parameters:
  - name: oneBranchTemplate
    type: string
    default: v2/OneBranch.Official.CrossPlat.yml

variables:
  WindowsContainerImage: 'onebranch.azurecr.io/windows/ltsc2022/vse2022:latest'

resources:
  repositories:
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

extends:
  template: ${{ parameters.oneBranchTemplate }}@templates
  parameters:
    featureFlags:
      WindowsHostVersion: 1ESWindows2022
    globalSdl:
      asyncSdl:
        enabled: false
    stages:
    - stage: main
      jobs:
      - job: Validate
        pool:
          type: windows
        variables: 
          ob_outputDirectory: '$(Build.SourcesDirectory)\drop'
        steps:
        - pwsh: ./build.ps1 -Target BuildCode
          displayName: Build
        - pwsh: dotnet test code.sln --configuration release --nologo --settings test\unittests\default.runsettings --results-directory $(ob_outputDirectory) --logger trx
          displayName: Test
        - task: onebranch.pipeline.signing@1
          displayName: Sign assemblies
          inputs:
            command: sign
            signing_profile: external_distribution
            files_to_sign: '**/*.dll'
            search_root: $(ob_outputDirectory)
        - pwsh: ./build.ps1 -Target GeneratePackages
          displayName: Package
        - task: onebranch.pipeline.signing@1
          displayName: Sign packages
          inputs:
            command: sign
            signing_profile: external_distribution
            files_to_sign: '**/*.nupkg'
            search_root: $(ob_outputDirectory)
